### ISSUE TITLE
how can I do delete operation?

### ISSUE THREAD

**Issue by antant-shenzhen-2013** [seomoz/pyreBloom#13]
hi,
I download and try a bit. AND can not find such delete operation? 
any suggestion?

BTW, i also wonder how this lib https://github.com/igrigorik/bloomfilter-rb do it by single bit..

**Comment by dlecocq** [comment]
Bloom filters do not support deletions. The operation for deletions used in [bloomfilter-rb](https://github.com/igrigorik/bloomfilter-rb/blob/master/lib/bloomfilter/redis.rb#L47) is wrong. The reason that bloom filters cannot support deletions is that they do not allow false negatives, and hash collisions are possible.

So, let's say 'foo' and 'bar' map to indexes (1, 2, 9) and (3, 4, 9) respectively. Our bloom filter containing both might look something like this:

```
# Add 'foo', add 'bar'
Position : 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
Bit value: 0 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 1
```

If you simply set all the bits for the indexes corresponding to a key to 0, then when removing 'bar', you'd get this:

```
# Add 'foo', add 'bar', remove 'bar'
Position : 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
Bit value: 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0
```

When you check to see if 'bar' is included, you'd see that it is not (which is expected):

```
bit_at(3) & bit_at(4) & bit_at(9) = 0 & 0 & 0 = false
```

But when you check to see if 'foo' is included, which _must_ be `true` to be a bloom filter, you get something altogether unexpected:

```
bit_at(1) & bit_at(2) & bit_at(9) = 1 & 1 & 0 = false
```

As for the single bit, the number of bits used per item is a function of the capacity and error rate of the bloom filter. The number of bits used per item is equal to the number of hashes needed to satisfy the capacity and error constraints.

Does that help?

**Comment by dlecocq** [comment]
FWIW, `bloomfilter-rb` has a bloom filter version and a counting version. If you use counting, then you _can_ implement deletions. However, it seems to me that their non-counting implementations should not allow deletions.

**Comment by antant-shenzhen-2013** [comment]
@dlecocq  got it, thx a lot.
