### ISSUE TITLE
Can't use specified redis db

### ISSUE THREAD

**Issue by hw20686832** [seomoz/pyreBloom#14]
When I want get a pyreBloon instance I can do this,
pyreBloom.pyreBloom("gbloomfilter", 100000000, 0.001, host='127.0.0.1', port=6379)
But I have no idea that how to use a specified redis db, anyway only can use db 0.

**Comment by dlecocq** [comment]
As of the version on master, you can now provide an optional `db` parameter when instantiating a bloom filter:

```python
pyreBloom.pyreBloom('key', 1000, 0.001, db=4)
```
