### ISSUE TITLE
Eventlet 

### ISSUE THREAD

**Issue by ppiccolo** [seomoz/pyreBloom#19]
Hi ...
using pyrebloom with celery and eventlet cause segmentation fault :(

any idea  ?

**Comment by dlecocq** [comment]
Are you using the same `pyreBloom` object across eventlets? The network communication is done in a C extension in this library and may well not play well with eventlet. You might be able to either:

- use a new `pyreBloom` object in each eventlet (depending on how long-lived the task is) OR
- use a pool of such objects OR
- use https://github.com/xupeng/bloomfilter-redis (the inspiration of this library, but implemented in pure python)

**Comment by ppiccolo** [comment]
Yes ... same object, I'll give a try to https://github.com/xupeng/bloomfilter-redis 

tnx
